### PR TITLE
Added smooth scrolling

### PR DESCRIPTION
**Pull request by ROODAY**
Is futureproof, add anymore #idnamehere links on the site and it will smooth scroll

### CODE REVIEW

**Comment by lengstrom** [comment]
Are we going to use jQuery in this project? @themichaelyang

**Comment by cchan** [comment]
I think that if we have to use JavaScript, we should use JQuery. Whatever
code we have to write will look nicer.

And since this is just a supplementary function, it shouldn't really matter
(like in the previous website, with _my_ smooth-scrolling.). We can even
have a <script> tag load the JQuery if you want, so we don't have to have
the extra HTTP request if the user doesn't have JS.

:{

**Comment by ROODAY** [comment]
i concur with @mathnerd3141

**Comment by ROODAY** [comment]
that moment when the request aint pulled

that moment when there's still no smooth scrolling

**Comment by lengstrom** [comment]
scrolls smoothly for me

**Pull request closed without merging**
